### ISSUE TITLE
On npm start the cli presents me this error. Bug of feature?

### ISSUE THREAD

**Issue by psavary** [syzer/which-db-we-using-this-week#2]
Savarys-MacBook-Pro:which-db-we-using-this-week philou$ **npm start**
​

> which-db-we-using-this-week@1.0.2 start /Users/philou/Documents/development/which-db-we-using-this-week
> node index
> ​
> This week we use CouchDb, because having a distributed db is crucial to our business.
> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> ​
> Error: spawn gm ENOENT
>     at exports._errnoException (util.js:874:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
>     at onErrorNT (internal/child_process.js:344:16)
>     at doNTCallback2 (node.js:439:9)
>     at process._tickCallback (node.js:353:17)
>     at Function.Module.runMain (module.js:469:11)
>     at startup (node.js:134:18)
>     at node.js:961:3
> ​
> npm ERR! Darwin 15.0.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
> npm ERR! node v4.2.1
> npm ERR! npm  v2.14.7
> npm ERR! code ELIFECYCLE
> npm ERR! which-db-we-using-this-week@1.0.2 start: `node index`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the which-db-we-using-this-week@1.0.2 start script 'node index'.
> npm ERR! This is most likely a problem with the which-db-we-using-this-week package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node index
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls which-db-we-using-this-week
> npm ERR! There is likely additional logging output above.
> ​
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/philou/Documents/development/which-db-we-using-this-week/npm-debug.log

**Comment by syzer** [comment]
please use `brew install graphicsmagick`
